<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-07-06 at 15:17:03.
 */
class CustomerServiceControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CustomerServiceController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CustomerServiceController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers CustomerServiceController::filters
     * @todo   Implement testFilters().
     */
    public function testFilters() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CustomerServiceController::accessRules
     * @todo   Implement testAccessRules().
     */
    public function testAccessRules() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CustomerServiceController::actionIndex
     * @todo   Implement testActionIndex().
     */
    public function testActionIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CustomerServiceController::actionNationalitySearch
     * @todo   Implement testActionNationalitySearch().
     */
    public function testActionNationalitySearch() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CustomerServiceController::actionCustomerSearch
     * @todo   Implement testActionCustomerSearch().
     */
    public function testActionCustomerSearch() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CustomerServiceController::actionSearch
     * @todo   Implement testActionSearch().
     */
    public function testActionSearch() {
         
        // true        
        $_REQUEST['action']= "search";                
        $_REQUEST['string']= "string test";             
        $_REQUEST['returnType']= "0";               
        $_REQUEST['retured']= "";               
       
        
        $this->assertTrue($this->object->Search($_REQUEST));
        
        
        // false
        $this->assertTrue($this->object->Search());
        
    }

    /**
     * @covers CustomerServiceController::actionWS
     * @todo   Implement testActionWS().
     */
    public function testActionWS() {
       
        // true                              
        $_REQUEST['string']= "string test";                                                   
        $this->assertTrue($this->object->WS($_REQUEST));                        
        
    }

    /**
     * @covers CustomerServiceController::decryptRJ256
     * @todo   Implement testDecryptRJ256().
     */
    public function testDecryptRJ256() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CustomerServiceController::actionpSearchProperty
     * @todo   Implement testActionpSearchProperty().
     */
    public function testActionpSearchProperty() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
