<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-07-06 at 11:49:56.
 */
class ExportedlettersControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ExportedlettersController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ExportedlettersController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ExportedlettersController::filters
     * @todo   Implement testFilters().
     */
    public function testFilters() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ExportedlettersController::accessRules
     * @todo   Implement testAccessRules().
     */
    public function testAccessRules() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ExportedlettersController::actionView
     * @todo   Implement testActionView().
     */
    public function testActionView() {
       
        // true 
        $this->assertTrue($this->object->view(1));
        $this->assertTrue($this->object->view(2));
                
        //false
        $this->assertTrue($this->object->view(-1));   
        
    }

    /**
     * @covers ExportedlettersController::actionCreate
     * @todo   Implement testActionCreate().
     */
    public function testActionCreate() {
        $_POST['Exportedletters']= "Exported Letter Test";                
        $this->assertTrue($this->object->create($_POST));
    }

    /**
     * @covers ExportedlettersController::actionUpdate
     * @todo   Implement testActionUpdate().
     */
    public function testActionUpdate() {
         // true 
        $this->assertTrue($this->object->update(1));
        $this->assertTrue($this->object->update(2));
        
        
        //false
        $this->assertTrue($this->object->update(-1));      
    }

    /**
     * @covers ExportedlettersController::actionDelete
     * @todo   Implement testActionDelete().
     */
    public function testActionDelete() {
        // true 
        $this->assertTrue($this->object->delete(1));
        $this->assertTrue($this->object->delete(2));
                
        //false
        $this->assertTrue($this->object->delete(-1));   
    }

    /**
     * @covers ExportedlettersController::actionIndex
     * @todo   Implement testActionIndex().
     */
    public function testActionIndex() {
         $this->assertTrue($this->object->index());   
    }

    /**
     * @covers ExportedlettersController::actionAdmin
     * @todo   Implement testActionAdmin().
     */
    public function testActionAdmin() {
        $this->assertTrue($this->object->admin());   
    }

    /**
     * @covers ExportedlettersController::loadModel
     * @todo   Implement testLoadModel().
     */
    public function testLoadModel() {
         // true 
        $this->assertTrue($this->object->loadModel(1));
        $this->assertTrue($this->object->loadModel(2));
                
        //false
        $this->assertTrue($this->object->loadModel(-1));  
    }

}
