<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-07-06 at 14:21:50.
 */
class ReportsControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ReportsController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ReportsController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ReportsController::filters
     * @todo   Implement testFilters().
     */
    public function testFilters() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReportsController::accessRules
     * @todo   Implement testAccessRules().
     */
    public function testAccessRules() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReportsController::actionCalulate
     * @todo   Implement testActionCalulate().
     */
    public function testActionCalulate() {
        
        //true
        $_POST['rows']= array("id");                
        $_POST['tables']= array("destination"); 
        $_POST['columns']= array("id"); 
        $_POST['data']= ""; 
        $_POST['conditions']= ""; 
        $_POST['page']= 0; 
        
        $this->assertTrue($this->object->Calulate($_POST));
        
        
        //false
        $_POST['rows']= "";                
        $_POST['tables']= ""; 
        $_POST['columns']= ""; 
        $_POST['data']= ""; 
        $_POST['conditions']= ""; 
        $_POST['page']= 0; 
        
        $this->assertTrue($this->object->Calulate($_POST));
        
    }

    /**
     * @covers ReportsController::actionExporttocsv
     * @todo   Implement testActionExporttocsv().
     */
    public function testActionExporttocsv() {        
        $this->assertTrue($this->object->Exporttocsv());           
    }

    /**
     * @covers ReportsController::actionIndex
     * @todo   Implement testActionIndex().
     */
    public function testActionIndex() {
        $this->assertTrue($this->object->Index());   
    }

    /**
     * @covers ReportsController::actionOpenTable
     * @todo   Implement testActionOpenTable().
     */
    public function testActionOpenTable() {        
        // true
        $this->assertTrue($this->object->OpenTable("destination"));   
        
        //false
        $this->assertTrue($this->object->OpenTable());
    }

    /**
     * @covers ReportsController::actionCalculateChart
     * @todo   Implement testActionCalculateChart().
     */
    public function testActionCalculateChart() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReportsController::percent
     * @todo   Implement testPercent().
     */
    public function testPercent() {            
        // true
        $this->assertTrue($this->object->percent(50,100));           
        $this->assertTrue($this->object->percent(75,100));
        
        // false
        $this->assertTrue($this->object->percent(10,0));
    }

}
