<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-07-06 at 15:04:16.
 */
class SiteControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var SiteController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SiteController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers SiteController::actions
     * @todo   Implement testActions().
     */
    public function testActions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SiteController::actionIndex
     * @todo   Implement testActionIndex().
     */
    public function testActionIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SiteController::actionError
     * @todo   Implement testActionError().
     */
    public function testActionError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SiteController::actionContact
     * @todo   Implement testActionContact().
     */
    public function testActionContact() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SiteController::actionLogin
     * @todo   Implement testActionLogin().
     */
    public function testActionLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SiteController::actionLogout
     * @todo   Implement testActionLogout().
     */
    public function testActionLogout() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SiteController::actionProfile
     * @todo   Implement testActionProfile().
     */
    public function testActionProfile() {
        
        // true 
        $this->assertTrue($this->object->Profile(1));   
        
        // false
        $this->assertTrue($this->object->Profile(-1));   
        
    }

    /**
     * @covers SiteController::actionsendEmail
     * @todo   Implement testActionsendEmail().
     */
    public function testActionsendEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SiteController::actionupdateUser
     * @todo   Implement testActionupdateUser().
     */
    public function testActionupdateUser() {
        
        $_POST['id']= 1;                
        $_POST['fname']= "First Name Test";                
        $_POST['lname']= "Last Name Test";                
        $this->assertTrue($this->object->updateUser($_POST));
        
        $_POST['id']= -1;                
        $_POST['fname']= "First Name Test";                
        $_POST['lname']= "Last Name Test";                
        $this->assertTrue($this->object->updateUser($_POST));
    }

}
