<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-07-06 at 15:55:18.
 */
class ProfilesTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Profiles
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Profiles;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Profiles::model
     * @todo   Implement testModel().
     */
    public function testModel() {
        $this->assertTrue($this->object->Model());
    }

    /**
     * @covers Profiles::tableName
     * @todo   Implement testTableName().
     */
    public function testTableName() {
        $this->assertTrue($this->object->tableName());
    }

    /**
     * @covers Profiles::rules
     * @todo   Implement testRules().
     */
    public function testRules() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Profiles::relations
     * @todo   Implement testRelations().
     */
    public function testRelations() {
        $this->assertTrue($this->object->relations());   
    }

    /**
     * @covers Profiles::attributeLabels
     * @todo   Implement testAttributeLabels().
     */
    public function testAttributeLabels() {
        $this->assertTrue($this->object->attributeLabels()); 
    }

    /**
     * @covers Profiles::search
     * @todo   Implement testSearch().
     */
    public function testSearch() {
        $this->assertTrue($this->object->search());   
    }

}
